Repository nextcloud/gallery, pull requests merged in 2018-04, with the labels that each got.

#421 Hide "No results found" tooltip on autocompletion
  js/vendor/nextcloud/share.js
Labels: 3. to review, backport-request, bug, feature:sharing

#424 [stable13] Hide "No results found" tooltip on autocompletion
  js/vendor/nextcloud/share.js
Labels: 3. to review, bug, feature:sharing

#326 Add confirmation button to share input
  css/share.css
  js/vendor/nextcloud/share.js
Labels: 3. to review, backport-request, design, enhancement

#425 Public page response
  css/public.css
  css/styles.css
  js/breadcrumb.js
  js/gallery.js
  js/galleryview.js
  lib/AppInfo/Application.php
  lib/Controller/PageController.php
  templates/public.php
  tests/unit/Controller/PageControllerTest.php
Labels: 3. to review, design, enhancement

#428 Fix error while clicking on the share link checkbox
  js/vendor/nextcloud/share.js
Labels: 3. to review, backport-request, bug, feature:sharing

#430 [stable13] Fix error while clicking on the share link checkbox
  .drone.yml
  js/vendor/nextcloud/share.js
Labels: 3. to review, bug, feature:sharing
