Repository nextcloud/gallery, pull requests merged in 2018-03, with the labels that each got.

#401 Fix gallery button hidden in folders without create permission
  css/gallerybutton.css
  js/gallerybutton.js
Labels: 3. to review, backport-request

#402 [stable13] Fix gallery button hidden in folders without create permission
  css/gallerybutton.css
  js/gallerybutton.js
Labels: 3. to review

#404 Fix controls position in gallery layout
  css/public.css
  css/styles.css
  js/app.js
Labels: 3. to review, backport-request, bug

#405 [stable13] Fix controls position in gallery layout
  css/public.css
  css/styles.css
  js/app.js
Labels: 3. to review, bug

#406 [stable13] Removed old code already present thanks to the files app
  css/share.css
Labels: 3. to review, design

#407 [stable13] create "file app" public share links if the slideshow is opened from ...
  js/galleryfileaction.js
  js/vendor/nextcloud/share.js
Labels: 3. to review, feature:sharing

#408 Fixed sharedwithlist selector
  css/share.css
Labels: 3. to review, design, regression

#414 Fix gallery buttons positionning
  css/gallerybutton.css
Labels: 3. to review, blocked by server, design, regression

#415 Fix "No results found" tooltip
  js/vendor/nextcloud/share.js
Labels: 3. to review, bug, feature:sharing

#412 Fix position of icons in "Share with" input field
  css/share.css
Labels: 3. to review, backport-request, bug, design, regression

#417 Fix UI while a share is being added
  js/vendor/nextcloud/share.js
Labels: 3. to review, bug, design, feature:sharing

#420 [stable13] Fix UI while a share is being added
  js/vendor/nextcloud/share.js
Labels: 3. to review, bug, design, feature:sharing

#419 [stable13] Fix "No results found" tooltip
  js/vendor/nextcloud/share.js
Labels: 3. to review, bug, feature:sharing

#418 [stable13] Fix position of icons in "Share with" input field
  css/share.css
Labels: 3. to review, bug, design, regression
