Repository nextcloud/gallery, pull requests merged in 2018-02, with the labels that each got.

#393 Fix share drop down in gallery not properly shown
  css/share.css
  js/vendor/nextcloud/share.js
Labels: 3. to review, backport-request, bug, design

#395 Move transifex config for updated l10n script
  .tx/config
Labels: 3. to review

#396 Remove unneeded files
  l10n/af_ZA.php
  l10n/bn_IN.php
  l10n/de_AT.php
  l10n/de_CH.php
  l10n/hi.php
  l10n/ku_IQ.php
  l10n/ms_MY.php
  l10n/pa.php
  l10n/si_LK.php
  l10n/sr@latin.php
  l10n/ug.php
Labels: 3. to review, technical debt

#394 [stable13] Fix share drop down in gallery not properly shown
  css/share.css
  js/vendor/nextcloud/share.js
Labels: 3. to review, bug, design

#399 Removed old code already present thanks to the files app
  css/share.css
Labels: 3. to review, backport-request, design, papercut
