Repository nextcloud/gallery, pull requests merged in 2018-08, with the labels that each got.

#456 Fixes the gallery app width
  css/styles.css
Labels: 3. to review, bug, design

#462 Bind scroll event to window
  js/app.js
Labels: 3. to review, bug, high

#457 Adjust ui to changes in server
  css/share.css
  css/styles.css
  js/app.js
  js/breadcrumb.js
  js/gallery.js
  js/galleryview.js
  js/slideshow.js
  js/slideshowcontrols.js
  templates/index.php
  templates/public.php
Labels: 3. to review, bug, design, regression
