Repository nextcloud/gallery, pull requests merged in 2019-06, with the labels that each got.

#526 🐛 FIX: sharing confirm Button
  css/share.css
Labels: 3. to review, papercut

#528 Correctly show errors when setting the password
  js/vendor/nextcloud/share.js
Labels: backport-request

#532 Fix gallery sorting buttons and remove filelist ref #16076
  css/gallerybutton.css
  templates/part.content.php
Labels: 2. developing, 3. to review, design, enhancement
